name: flutterjs
description: A sample command-line application.
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

workspace:
  - examples/counter_app/
  - packages/dev_utils/
  - packages/flutterjs_tools/
  - packages/flutterjs_gen/
  - packages/flutterjs_analyzer/
  - packages/engine/

environment:
  sdk: ^3.10.0-227.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args:
  flutterjs_analyzer:
    path: packages/flutterjs_analyzer
  engine:
    path: packages/engine
  flutterjs_gen:
    path: packages/flutterjs_gen
  flutterjs_tools:
    path: packages/flutterjs_tools
  dev_utils:
    path: packages/dev_utils    
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
