name: flutterjs
description: A powerful framework for building web applications using Dart, compiled to efficient JavaScript and CSS.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/flutterjsdev/flutterjs
homepage: https://flutterjs.dev
license: BSD-3-Clause

executables:
  flutterjs: flutterjs

workspace:
  - examples/counter/
  - examples/routing_app/
  - examples/material_demo/
  - examples/multi_file_test/
  - packages/flutterjs_dev_utils/
  - packages/flutterjs_tools/
  - packages/flutterjs_gen/
  - packages/dart_analyzer/
  - packages/flutterjs_core/
  - packages/flutterjs_dev_tools/
  - packages/pubjs/
  - packages/flutterjs_seo/
  - packages/flutterjs_builder/
  - examples/pub_test_app/
  - examples/flutterjs_website/

environment:
  sdk: ^3.10.0-227.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  analyzer: ^8.4.1
  args:
  archive: ^4.0.7
  code_builder: ^4.11.1
  dart_analyzer: any
  flutterjs_core: any
  flutterjs_gen: any
  flutterjs_tools: any
  flutterjs_dev_utils: any    
  flutterjs_dev_tools: any    


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6



