name: flutterjs
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

workspace:
  - examples/counter_app/

environment:
  sdk: ^3.10.0-227.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: 

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
