name: flutterjs
description: A sample command-line application.
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

executables:
  flutterjs: flutterjs

workspace:
  - examples/counter/
  - examples/routing_app/
  - examples/material_demo/
  - examples/multi_file_test/
  - packages/flutterjs_dev_utils/
  - packages/flutterjs_tools/
  - packages/flutterjs_gen/
  - packages/dart_analyzer/
  - packages/flutterjs_core/
  - packages/flutterjs_dev_tools/
  - packages/pubjs/
  - packages/flutterjs_seo/
  - packages/flutterjs_seo/example/

environment:
  sdk: ^3.10.0-227.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  analyzer: ^8.4.1
  args:
  dart_analyzer: any
  flutterjs_core: any
  flutterjs_gen: any
  flutterjs_tools: any
  flutterjs_dev_utils: any    
  flutterjs_dev_tools: any    


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6


