name: flutterjs_animation
publish_to: 'none'
version: 1.0.0
resolution: workspace
description: FlutterJS implementation of animation functionalities.

homepage: https://flutterjs.dev
repository: https://github.com/flutterjs/flutterjs_animation
issue_tracker: https://github.com/flutterjs/flutterjs_animation/issues

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_animation"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"











