name: flutterjs_cupertino
publish_to: 'none'
version: 1.0.0
resolution: workspace
description: FlutterJS implementation of cupertino functionalities.

homepage: https://flutterjs.dev
repository: https://github.com/flutterjs/flutterjs_cupertino
issue_tracker: https://github.com/flutterjs/flutterjs_cupertino/issues

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_cupertino"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"












