name: flutterjs_dev_tools
publish_to: 'none'
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  shelf: ^1.4.0
  intl: any
  shelf_cors_headers: ^0.1.0
  shelf_multipart: ^2.0.1
  path: ^1.8.0
  args: ^2.4.0
  http: ^1.1.0
  watcher: ^1.1.4
  flutterjs_core: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6











