name: flutterjs_gestures
version: 0.1.0
description: A FlutterJS package

homepage: https://github.com/flutterjs/flutterjs_gestures
repository: https://github.com/flutterjs/flutterjs_gestures
issue_tracker: https://github.com/flutterjs/flutterjs_gestures/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_gestures"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"
