name: flutterjs_runtime
version: 0.1.0
description: FlutterJS core runtime implementation

homepage: https://github.com/flutterjs/flutterjs_runtime
repository: https://github.com/flutterjs/flutterjs_runtime
issue_tracker: https://github.com/flutterjs/flutterjs_runtime/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_runtime"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"
