name: flutterjs_seo
version: 0.1.0
description: SEO metadata management for FlutterJS Applications

homepage: https://flutterjs.dev
repository: https://github.com/flutterjs/flutterjs_seo
issue_tracker: https://github.com/flutterjs/flutterjs_seo/issues

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

# FlutterJS metadata
x-flutterjs:
  npm_package: "@flutterjs/flutterjs_seo"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"
