name: flutterjs_vdom
publish_to: 'none'
version: 1.0.0
resolution: workspace
description: FlutterJS Virtual DOM implementation

homepage: https://flutterjs.dev
repository: https://github.com/flutterjs/flutterjs_vdom
issue_tracker: https://github.com/flutterjs/flutterjs_vdom/issues

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_vdom"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"











