name: flutterjs_vdom
version: 0.1.0
description: FlutterJS Virtual DOM implementation

homepage: https://github.com/flutterjs/flutterjs_vdom
repository: https://github.com/flutterjs/flutterjs_vdom
issue_tracker: https://github.com/flutterjs/flutterjs_vdom/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_vdom"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"
