name: flutterjs_server
version: 1.0.0
description: HTTP server framework for Node.js written in Dart. Compile Dart to JavaScript and run on Node.js.

homepage: https://flutterjs.dev
repository: https://github.com/flutterjsdev/flutterjs
issue_tracker: https://github.com/flutterjsdev/flutterjs/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
