name: flutterjs_core
description: Core architecture and primitives for the FlutterJS framework.
version: 1.0.0
repository: https://github.com/flutterjsdev/flutterjs/tree/main/packages/flutterjs_core
homepage: https://flutterjs.dev
license: BSD-3-Clause

environment:
  sdk: ^3.10.0-278.0.dev

# Add regular dependencies here.
dependencies:
  analyzer: ^8.4.1
  path: ^1.9.0
  flutterjs_dev_utils:
    path: ../flutterjs_dev_utils

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
