name: flutterjs_core
publish_to: 'none'
description: Core architecture and primitives for the FlutterJS framework.
version: 1.0.0
resolution: workspace
repository: https://github.com/flutterjsdev/flutterjs/tree/main/packages/flutterjs_core
homepage: https://flutterjs.dev
license: BSD-3-Clause

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0
  collection: ^1.18.0
  crypto: ^3.0.3
  analyzer: ^8.4.1
  path: ^1.9.0
  flutterjs_dev_utils:
    path: ../flutterjs_dev_utils

dev_dependencies:
  meta: ^1.11.0
  collection: ^1.18.0
  crypto: ^3.0.3
  lints: ^6.0.0
  test: ^1.25.6













