name: flutterjs_tools
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.0-278.0.dev

dependencies:
  path: ^1.9.0
  flutterjs_core: any
  flutterjs_analyzer: any
  flutterjs_dev_utils: any
  flutterjs_dev_tools: any
  flutterjs_gen: any
  args: ^2.7.0
  analyzer: ^8.4.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
