name: flutterjs_tools
publish_to: 'none'
description: FlutterJS implementation of tools functionalities.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.0
  flutterjs_core: any
  dart_analyzer: any
  flutterjs_dev_utils: any
  flutterjs_dev_tools: any
  flutterjs_gen: any
  pubjs: any
  args: ^2.7.0
  analyzer: ^8.4.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6











