name: flutterjs_cupertino_example
description: Example app for flutterjs_cupertino

publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter











