name: flutterjs_analyzer
publish_to: 'none'
version: 1.0.0
resolution: workspace
description: FlutterJS Analyzer - Dart widget analyzer

homepage: https://flutterjs.dev
repository: https://github.com/flutterjs/flutterjs_analyzer
issue_tracker: https://github.com/flutterjs/flutterjs_analyzer/issues

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/analyzer"
  implementation_language: "javascript"
  js_entry: "flutterjs_analyzer/src/index.js"












