name: flutterjs_analyzer
version: 1.0.0
description: FlutterJS Analyzer - Dart widget analyzer

homepage: https://github.com/flutterjs/flutterjs_analyzer
repository: https://github.com/flutterjs/flutterjs_analyzer
issue_tracker: https://github.com/flutterjs/flutterjs_analyzer/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/analyzer"
  implementation_language: "javascript"
  js_entry: "flutterjs_analyzer/src/index.js"
