name: flutterjs_services
version: 1.0.0
description: A FlutterJS package

homepage: https://github.com/flutterjs/flutterjs_services
repository: https://github.com/flutterjs/flutterjs_services
issue_tracker: https://github.com/flutterjs/flutterjs_services/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# FlutterJS metadata
flutterjs:
  npm_package: "@flutterjs/flutterjs_services"
  implementation_language: "javascript"
  js_entry: "js/src/index.js"
