name: dart_analyzer
publish_to: 'none'
description: Core dart_analyzer implementation for FlutterJS.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  path: ^1.9.0
  analyzer: ^10.0.1 
  flutterjs_dev_tools: any



dev_dependencies:
  crypto: ^3.0.3
  lints: ^6.0.0
  test: ^1.25.6













