name: pubjs
description: A decentralized package registry and management tool for FlutterJS, enabling resolving standard Dart packages to JavaScript implementations via Git-based registry.
version: 0.0.1
publish_to: 'none'
resolution: workspace
environment:
  sdk: ^3.10.0-278.0.dev


dependencies:
  args: ^2.4.2
  path: ^1.8.3
  http: ^1.1.0
  yaml: ^3.1.2
  crypto: ^3.0.3
  meta: ^1.10.0
  archive: ^4.0.7
  analyzer: ^8.4.1
  code_builder: ^4.11.1
  flutterjs_builder:
    path: ../flutterjs_builder

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
