name: pubjs
description: A decentralized package registry and management tool for FlutterJS, enabling resolving standard Dart packages to JavaScript implementations via Git-based registry.
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  http: ^1.1.0
  yaml: ^3.1.2
  meta: ^1.10.0
  archive: ^4.0.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
