name: flutterjs_seo_example
description: Example app for flutterjs_seo
# resolution: workspace
publish_to: 'none'
environment:
  sdk: ^3.10.0-278.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
