name: flutterjs_seo_example
description: Example app for flutterjs_seo
resolution: workspace
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'   # REQUIRED for workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
